FROM node:latest as base

WORKDIR /home/node/services-email

COPY ./services-email/package*.json ./

RUN npm i

COPY ./services-email/ ./

FROM base as production

ENV NODE_PATH=./build

RUN npm run build